"""Turn assets/icons/*.svg (Tabler outline icons) into ui/src/FA11y.UI/Theme/Icons.xaml.

Each icon becomes one Geometry resource named Icon.<file name>, in a 24 unit
box. The window draws them with a 2 unit stroke and round caps (see
Controls/IconBadge.cs), like the wx window does. Run from anywhere:

    python ui/tools/gen_icons.py

Supported SVG elements: path, line, circle, rect, polyline, polygon.
"""
from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
ICON_DIR = os.path.join(ROOT, "assets", "icons")
OUTPUT = os.path.join(ROOT, "ui", "src", "FA11y.UI", "Theme", "Icons.xaml")
SVG = "{http://www.w3.org/2000/svg}"


def num(value: str | None, default: float = 0.0) -> float:
    return float(value) if value not in (None, "") else default


def fmt(value: float) -> str:
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if text in ("", "-0") else text


def circle(cx: float, cy: float, r: float) -> str:
    return (f"M{fmt(cx - r)},{fmt(cy)} A{fmt(r)},{fmt(r)} 0 1 1 {fmt(cx + r)},{fmt(cy)} "
            f"A{fmt(r)},{fmt(r)} 0 1 1 {fmt(cx - r)},{fmt(cy)} Z")


def rect(x: float, y: float, w: float, h: float, rx: float, ry: float) -> str:
    if not rx and not ry:
        return f"M{fmt(x)},{fmt(y)} H{fmt(x + w)} V{fmt(y + h)} H{fmt(x)} Z"
    rx = rx or ry
    ry = ry or rx
    return (f"M{fmt(x + rx)},{fmt(y)} H{fmt(x + w - rx)} A{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(x + w)},{fmt(y + ry)} "
            f"V{fmt(y + h - ry)} A{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(x + w - rx)},{fmt(y + h)} "
            f"H{fmt(x + rx)} A{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(x)},{fmt(y + h - ry)} "
            f"V{fmt(y + ry)} A{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(x + rx)},{fmt(y)} Z")


def points(value: str, close: bool) -> str:
    nums = [float(n) for n in value.replace(",", " ").split()]
    pairs = list(zip(nums[0::2], nums[1::2]))
    if not pairs:
        return ""
    data = f"M{fmt(pairs[0][0])},{fmt(pairs[0][1])} " + " ".join(f"L{fmt(x)},{fmt(y)}" for x, y in pairs[1:])
    return data + (" Z" if close else "")


def element_path(el: ET.Element) -> str:
    tag = el.tag.replace(SVG, "")
    if tag == "path":
        if el.get("stroke") == "none":
            return ""  # Tabler's invisible bounding box
        return " ".join((el.get("d") or "").split())
    if tag == "line":
        return f"M{fmt(num(el.get('x1')))},{fmt(num(el.get('y1')))} L{fmt(num(el.get('x2')))},{fmt(num(el.get('y2')))}"
    if tag == "circle":
        return circle(num(el.get("cx")), num(el.get("cy")), num(el.get("r")))
    if tag == "rect":
        return rect(num(el.get("x")), num(el.get("y")), num(el.get("width")), num(el.get("height")),
                    num(el.get("rx")), num(el.get("ry")))
    if tag in ("polyline", "polygon"):
        return points(el.get("points") or "", tag == "polygon")
    return ""


def convert(path: str) -> str:
    root = ET.parse(path).getroot()
    return " ".join(p for p in (element_path(el) for el in root.iter()) if p)


def main() -> int:
    names = sorted(f[:-4] for f in os.listdir(ICON_DIR) if f.endswith(".svg"))
    lines = [
        '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
        '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
        '    <!-- Generated by ui/tools/gen_icons.py from assets/icons/*.svg. Do not edit by hand. -->',
    ]
    for name in names:
        data = convert(os.path.join(ICON_DIR, name + ".svg"))
        lines.append(f'    <Geometry x:Key="Icon.{name}">{data}</Geometry>')
    lines.append("</ResourceDictionary>")
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(names)} icons to {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
